services:

  ignition:
    image: ignition_dev
    container_name: ignitiondev_ignition
    hostname: ignitiondev_ignition
    restart: unless-stopped
    user: 0:0  # Run as Root
    build:
      context: ignition-build
      dockerfile: ignition_custom.dockerfile
      args:
        IGNITION_VERSION: 8.1.40
    networks:
      - rtmd-network
    ports:
      - '8089:8088' # HTTP Port
      - '8001:8000' # Debug Mode ('-d' flag) Remote JVM Debugging, conflicts with Portainer @ 8000
    command: >
      -n ignitiondev
      -d
      --
      -Dignition.allowunsignedmodules=true
    environment:
      - ACCEPT_IGNITION_EULA=Y
      - DISABLE_QUICKSTART=true
      - GATEWAY_ADMIN_USERNAME=admin
      - GATEWAY_ADMIN_PASSWORD=password
      - IGNITION_EDITION=standard
      - TZ=America/New_York
      - GATEWAY_MODULES_ENABLED=all
    volumes:
      - gateway-data:/usr/local/bin/ignition/data

volumes:
  gateway-data:
    name: 'ignitiondev_data'

networks:
  rtmd-network:
    name: 'rtmd-network'
