site_name: !ENV SITE_NAME
site_url: "https://hydra-mqtt.netlify.app/"
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expanded
#    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.path
    - toc.follow
    - search.suggest
    - search.highlight
#    - content.action.edit
#    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
  palette:
     - scheme: custom
#  palette:
#    - scheme: slate
#      primary: black
#      accent: blue
  logo: assets/hydra.png
  favicon: assets/hydra.png

# Admonitions
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2 # Define which header level (##) to use as top level TOC. Default: 1

  # Improves bold and italic handling
  #   https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem:
      smart_enable: all

  # Link related features
  #   https://facelessuser.github.io/pymdown-extensions/extensions/magiclink/
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material

  # For creating symbols such as copyright
  #   https://facelessuser.github.io/pymdown-extensions/extensions/smartsymbols/
  - pymdownx.smartsymbols

# Admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Annotations
  - attr_list
  - md_in_html
  - pymdownx.superfences

# Buttons
  - attr_list

# Code Blocks
  - pymdownx.highlight:
      anchor_linenums: true
#      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences

# Content Tabs
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Data Tables
  - tables

# Diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Footnotes
  - footnotes

# Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

# Grids
  - attr_list
  - md_in_html

# Icons, Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Images
  - attr_list
  - md_in_html

# Lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

# MathJax
  - pymdownx.arithmatex:
      generic: true

# Tooltips
  - abbr
  - attr_list
  - pymdownx.snippets

extra_css:
  - stylesheets/scheme.css

extra_javascript:
# Data Tables
  - assets/js/tablesort.min.js # Download from https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - assets/js/tablesort.js # From Material for MKDocs
#  - assets/js/tablesort-deleteme.js # Download from https://github.com/tristen/tablesort

# Mathjax
  - assets/js/mathjax.js # From Material for MKDocs
#  - https://polyfill.io/v3/polyfill.min.js?features=es6 # No Content
  - assets/js/tex-mml-chtml.js # Download from https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # Download from https://github.com/mathjax/MathJax/tree/master/es5/output/chtml/fonts/woff-v2
  - assets/js/output/chtml/fonts/woff-v2/MathJax_Main-Italic.woff
  - assets/js/output/chtml/fonts/woff-v2/MathJax_Math-Regular.woff
  - assets/js/output/chtml/fonts/woff-v2/MathJax_Zero.woff

plugins:
  - search
  - include_dir_to_nav:
      reverse_sort_directory: true
  - offline
  - include-markdown

repo_url: https://github.com/m-r-mccormick/Hydra-MQTT
edit_uri: edit/main/docs/src

nav:
- index.md
- Pages
- changelog.md
